"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var author_controller_1 = require("../controler/author.controller");
var router = (0, express_1.Router)();
router.get('/getAllAuther', author_controller_1.default.getAuther);
router.post('/create', author_controller_1.default.createAuthor);
router.delete('/delete/:id', author_controller_1.default.deleteAuthor);
router.put('/update/:id', author_controller_1.default.updateAuthor);
exports.default = router;
